export const MAKE_REQ = "MAKE_REQ"
export const REQ_GETALL_SUCC = "REQ_GETALL_SUCC"
export const REQ_GETALL_FAIL = "REQ_GETALL_FAIL"

export const OPEN_POPUP = "OPEN_POPUP"
export const REQ_ADD_SUCC = "REQ_ADD_SUCC"
export const REQ_UPDATE_SUCC = "REQ_UPDATE_SUCC"
export const REQ_DELETE_SUCC = "REQ_DELETE_SUCC"

export const REQ_GETBYCODE_SUCC = "REQ_GETBYCODE_SUCC"

// Projects 
export const PROJECTS_MAKE_REQ = "PROJECTS_MAKE_REQ"
export const PROJECTS_REQ_GETALL_SUCC = "PROJECTS_REQ_GETALL_SUCC"
export const PROJECTS_REQ_GETALL_FAIL = "PROJECTS_REQ_GETALL_FAIL"

export const PROJECTS_OPEN_POPUP = "PROJECTS_OPEN_POPUP"
export const PROJECTS_REQ_ADD_SUCC = "PROJECTS_REQ_ADD_SUCC"
export const PROJECTS_REQ_UPDATE_SUCC = "PROJECTS_REQ_UPDATE_SUCC"
export const PROJECTS_REQ_DELETE_SUCC = "PROJECTS_REQ_DELETE_SUCC"

export const PROJECTS_REQ_GETBYCODE_SUCC = "PROJECTS_REQ_GETBYCODE_SUCC"